// Proof-of-concept: drive the Sentry Cocoa SDK from a *pure* C++ file.
//
// There is no Objective-C, no `.mm`, and no `@import` here. The only bridge is
// the generated `sentry-Swift.h` header, which projects the `sentry` Swift
// shim module (built with C++ interoperability) into the C++ `sentry::`
// namespace.

#include <iostream>

// Generated by SwiftPM from the `sentry` shim module when it is compiled with
// `-cxx-interoperability-mode=default`. Depending on the toolchain layout the
// include may need to be `<sentry/sentry-Swift.h>`; see the README.
#include "sentry-Swift.h"

int main() {
    std::cout << "[C++] Initializing Sentry from a pure C++ translation unit..."
              << std::endl;

    // sentry::init maps to the Swift shim's `init(_:)`, which calls
    // SentrySDK.start under the hood.
    sentry::init("https://a92d50327ac74b8b9aa4ea80eccfb267@o447951.ingest.sentry.io/5428557");

    std::cout << "[C++] Capturing a test message..." << std::endl;
    sentry::captureMessage("Hello from a pure C++ translation unit!");

    std::cout << "[C++] Shutting Sentry down..." << std::endl;
    // sentry::shutdown maps to the Swift shim's `shutdown()`, which calls
    // SentrySDK.close under the hood.
    sentry::shutdown();

    std::cout << "[C++] Done." << std::endl;
    return 0;
}
